name: Learning GitHub Actions

on:
  push:
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Start
        run: echo "CI Started"

      - name: Step 2 - List Files
        run: ls 
      - name: Step 3 - Finish
        run: echo "CI Finished Successfully!"

