name: Learning GitHub Actions

on:
  push:
    
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Start
        run: echo "CI Started"
      - name: Step 2 - Run Tests
        run: echo "Running Tests..."
      - name: Step -3 starts
        run: ls -la
      - name: Step 3 - Finish
        run: echo "CI Finished Successfully"

